services:
  app:
    image: openjdk:17-jdk-slim
    container_name: bt-interview
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=TestUser
      - DB_PASSWORD=TestPassword
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_DB: TestDB
      POSTGRES_USER: TestUser
      POSTGERS_PASSWORD: TestPassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
